server:
  port: 6600

spring:
  application:
    name: edu-crowd-order
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka