server:
  port: 7000
spring:
  application:
    name: edu-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiwnDz3/IIE40RkwHGdrxRTlzohcjQTwZR8YejmS/CLsYSYUvcKwT1gMu1dyrZZNRnJLJMLRkJvmDoLcZqJPy398YvpKvv0OaItVloFot9lcZdbjQrTHLlLTIkJyxi2/93ugoJZPvv72MNwLGh52V+1OPIHuMax3BHD58KpgG3tUcFT/21W7BPSb2w+a7mt1ZCQyeGjCeIKi9y5RvePI6JJnRXJpvHCz2URElZpxi+pmVl+I3nBdf/cp/tWEhj7F0sId66WvFtFj+EyyqTMHJ7vas030GwjWzyHNlZoikcaMxG7ynSREe44t9QUmJ6KlWszXi9dx5S9WfDLzLslmYaQIDAQAB
    app-id: 2021000118602150
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCt9qrfUonbBcUgj50M+lZFUS+8DlpjUlknj5ZsfP/NMA/8qVXhdkEs5XZ2RA9uKR6BLE2yYTRv55/Hl0O7q9UvlguKTUerNjHZZmHxAQAa2tuiSixycVnWJ0whqhTU5+n3DRAzNDd5tDMi7aqaf+cSOJB8rB1ncy9Jbm27utgkiutMRVQrQ6wfTlz40l0oFLErTWnew57dsacVHWdmjaHKhpiQgtQcN9Hyl99ZXVeQ5I1w5+1dUsjgHsUkNLOjvgA5L+Vtdsjo2vtY3ZMkCayx1oAHBye4aK70UOczoOiNlArXu1dDJlGzfO09SdgR+RHCOLdVbHguCe2MDfOYtl/9AgMBAAECggEBAKlQzVpykS4VXZmlbav18wWgUR9tsNe+jHuOq0+IEch5oPW/MpEwcZrq8vOEpqgHaWM75ZtaNJk+DStLtGbyhZm9JhpDwR+Irdf0aBsTaDC7Fs3L95qjbFadBOI3EfNujS8hDcVoax4PHz49p7CcECCR4T8Wnb/UQg/sZO00m65jzmyUnA+QWmlcCH5K4OtvpVIxJH/2dIXsJjQ0dZ2tmsMzM/mSvK/QAG1c8iHNklnHI5yduLddPpQLLf5TMb4FC70OPbLktxy5W0JA5BsJNcj6pnr8LGccxNQ5VQq6W3C/tfQKWqwgijb4UqHRrD+BUTk4ZJsAUSTDQiKHozQrD0ECgYEA+nszHv148i0CivFfxFW0OLKLZ2u+WyS6TvcNaQs7s2my0+oVeExtXuy3Usm7b1mQz+qHcnrAtAw/tn8d/GqpALwLtbnXqziLNdYTg9Q5Q9PONDK2loLOjm32Yi9kKS80bFSSOoFsSGG0ofct5xfOMnTlu8SCTkNDclrhpkus+PUCgYEAscvhsu9G90PAMbMexI8LocMuTAC4+brHDeJAd+gXAR4f02Z7hmRRExKaKeqNvCrdDMZemK0i2HwVLpoJ/i7y8OtyPov3oL7EHNQTlY+bLB6TEP58MAHZK4qr3+NeqxSUAe8MUTPCV8J8L2Vlg9sKh3ptslsPFiy8/3ecB1LfBekCgYEA6f1JBjw3TdSqOW2+zsRZNVXlUFmgW7h1quqzRlvOC45EFh7oq5aJ3VE4+Eenpx9+XhxzJ4hwmEGRC0S4mGJzOlJwhfTz+ek6crJnTJFmZWxphu2REA1mNDuZHKO055xHVqOybqEUrJFJkrw7z1O3tf7p1Xx/VekUCrHHdfffwDkCgYEApIcMtq6htxLk+ZjNsgrFMs4RO5e3lLD4nqpuCgelsg0UWmYNjNGsDMA8FOnOewAXSkkPJK2i/z3jxBobgTIk8jiOob6YShH+HMdL0Czx5SPt5933Qd2T/6z1W9tlsV77j8aMWWBSSS/aB2oHRLsfxTrP5CpLjbOcubMPmd9gLnECgYAGVe03gxnmBfYLoKv5xDN9a7KAmQ36VBMzyvYSO1Z54sFB8F3dPErJ3oKEK/sbS1iU9WRKsTWbrobTEZd0U2RODYoMfnaJCxlRboeXLHN3JjadJ51YJ9v4A32775TduU3RH7VgYMYgjFGBrP7nktvg6nGASkaJFYjLGN/gzg8HBA==
    notify-url: http://4ury9y.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2