server:
  port: 4000
  
spring:  application:    name: edu-croed-auth
  thymeleaf:    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
      
short: 
  message: 
    appcode: 847cd97706bd462cafc66ba88b366b74
    host: https://intlsms.market.alicloudapi.com
    path: /comms/sms/groupmessaging
    method: POST
    sign: "0"
    skin: "0000000"
    
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000