server:
  port: 80
  
spring:  application:    name: edu-crowd-zuul
  redis:    host: 127.0.0.1
  session:    store-type: redis
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  ignored-services: "*" #忽略原名微服务名称
  sensitive-headers: "*" #在zuul向其他微服务发起重定向时保持原本信息  routes:               #自定义路由名称    crowd-portal:       #自定义路由规则名称
      service-id: edu-croed-auth  #针对edu-croed-auth设置路由规则
      path: /** #表示多层目录
    crowd-project:       #自定义路由规则名称
      service-id: edu-crowd-project  #针对edu-croed-project设置路由规则
      path: /project/** #表示多层目录
    crowd-order:       #自定义路由规则名称
      service-id: edu-crowd-order  #针对edu-crowd-order设置路由规则
      path: /order/** #表示多层目录
    crowd-pay:
      service-id: edu-crowd-pay
      path: /pay/**
      
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000